version: "3.9"
services:
  auth:
    image: auth
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_BG_HOST=${REDIS_HOST}
      - REDIS_ADMIN_HOST=${REDIS_HOST}
      - REDIS_ADMIN_BG_HOST=${REDIS_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - PYTHONPATH=/app/src
      - OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST=x-request-id
    working_dir: /app/src
    depends_on:
      - redis
    command: >
      sh -c "python3 /app/waiters/wait_for_redis.py && \
             python3 /app/waiters/wait_for_postgresql.py && \
             alembic -c ../alembic.ini upgrade head && \
             gunicorn --workers 4 --bind 0.0.0.0:8000 wsgi_app:app"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:13"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx/simple_config.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth
