version: '2.2'
services:
    logstash:
        image: logstash:7.10.1
        environment:
          ES_HOST: "elasticsearch:9200"
        ports:
          - "5044:5044/udp"
        volumes:
          # Монтируем файл с конфигурацией logstash
          - ./deploy/logstash.conf:/config/logstash.conf:ro
        # Запускаем с указанием конфигурационного файла
        command: logstash -f /config/logstash.conf
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
      environment:
        # Указываем ES запуститься в одном экземпляре
        discovery.type: single-node
      ports:
        - 9200:9200
      volumes:
        - /tmp/esdata:/tmp/elasticsearch/data
  # Обратите внимание: не стоит использовать для ELK тот же ES, который задействован для полнотекстового поиска в вашем сервисе

    kibana:
      image: docker.elastic.co/kibana/kibana:7.10.2
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch
